apiVersion: v2
name: dell-container-storage-modules
description: A Helm chart that references the official "dell-container-storage-modules" Helm chart.
type: application
version: 1.8.0
dependencies:
  - name: container-storage-modules
    version: 1.8.0
    repository: https://dell.github.io/helm-charts
