apiVersion: v2
name: keda
description: A Helm chart to refer the official "keda" helm chart
type: application
version: 2.17.0
dependencies:
  - name: keda
    version: 2.17.0
    repository: https://kedacore.github.io/charts
