apiVersion: v2
name: local-ai
description: A Helm chart that references the official "local-ai" Helm chart.
type: application
version: 3.4.2
dependencies:
  - name: local-ai
    version: 3.4.2
    repository: https://go-skynet.github.io/helm-charts/
